/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'quiche-napi.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./quiche-napi.android-arm64.node')
          } else {
            nativeBinding = require('@quiche-nwep/napi-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'quiche-napi.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./quiche-napi.android-arm-eabi.node')
          } else {
            nativeBinding = require('@quiche-nwep/napi-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'quiche-napi.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./quiche-napi.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@quiche-nwep/napi-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'quiche-napi.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./quiche-napi.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@quiche-nwep/napi-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'quiche-napi.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./quiche-napi.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@quiche-nwep/napi-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'quiche-napi.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./quiche-napi.darwin-universal.node')
      } else {
        nativeBinding = require('@quiche-nwep/napi-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'quiche-napi.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./quiche-napi.darwin-x64.node')
          } else {
            nativeBinding = require('@quiche-nwep/napi-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'quiche-napi.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./quiche-napi.darwin-arm64.node')
          } else {
            nativeBinding = require('@quiche-nwep/napi-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'quiche-napi.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./quiche-napi.freebsd-x64.node')
      } else {
        nativeBinding = require('@quiche-nwep/napi-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'quiche-napi.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./quiche-napi.linux-x64-musl.node')
            } else {
              nativeBinding = require('@quiche-nwep/napi-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'quiche-napi.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./quiche-napi.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@quiche-nwep/napi-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'quiche-napi.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./quiche-napi.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@quiche-nwep/napi-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'quiche-napi.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./quiche-napi.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@quiche-nwep/napi-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'quiche-napi.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./quiche-napi.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@quiche-nwep/napi-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'quiche-napi.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./quiche-napi.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@quiche-nwep/napi-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'quiche-napi.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./quiche-napi.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@quiche-nwep/napi-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'quiche-napi.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./quiche-napi.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@quiche-nwep/napi-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'quiche-napi.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./quiche-napi.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@quiche-nwep/napi-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { Config, Connection, H3Config, H3Connection, PacketType, parseHeader, negotiateVersion, retry, isVersionNegotiation, StartupExitReason, CongestionControlAlgorithm, PROTOCOL_VERSION, MAX_CONN_ID_LEN, MIN_CLIENT_INITIAL_LEN, generateCid, encodeAlpn, nwepAlpn, nwepAndH3Alpn } = nativeBinding

module.exports.Config = Config
module.exports.Connection = Connection
module.exports.H3Config = H3Config
module.exports.H3Connection = H3Connection
module.exports.PacketType = PacketType
module.exports.parseHeader = parseHeader
module.exports.negotiateVersion = negotiateVersion
module.exports.retry = retry
module.exports.isVersionNegotiation = isVersionNegotiation
module.exports.StartupExitReason = StartupExitReason
module.exports.CongestionControlAlgorithm = CongestionControlAlgorithm
module.exports.PROTOCOL_VERSION = PROTOCOL_VERSION
module.exports.MAX_CONN_ID_LEN = MAX_CONN_ID_LEN
module.exports.MIN_CLIENT_INITIAL_LEN = MIN_CLIENT_INITIAL_LEN
module.exports.generateCid = generateCid
module.exports.encodeAlpn = encodeAlpn
module.exports.nwepAlpn = nwepAlpn
module.exports.nwepAndH3Alpn = nwepAndH3Alpn
